version: '3' 

services:
  app:
    build:
      context: ./ 
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3000"]
    ports:
      - "3000:3000"
      - "8000:8000" 
    depends_on:
      - db 

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
